global.MEASURING_PAYLOAD_TYPE_COMPLETE_EULER           = '16';
global.MEASURING_PAYLOAD_TYPE_EXTENDED_QUATERNION      = '2';
global.MEASURING_PAYLOAD_TYPE_RATE_QUANTITIES_WITH_MAG = '20';

global.globalConnectedSensors = [];
